# Generated by Django 2.2.7 on 2019-11-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nu_Processo', models.BigIntegerField()),
                ('dt_Processo', models.CharField(max_length=45)),
                ('ar_Processo', models.CharField(max_length=45)),
                ('vl_Processo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cod_TipoProcesso', models.IntegerField()),
                ('cod_Materia', models.IntegerField()),
                ('cod_Forma', models.IntegerField()),
            ],
        ),
    ]
